package object

import (
	"testing"

	"github.com/rkolesnichenko/rpsl/ast"
)

// ruleSet collects the diagnostic rules present, for order-independent assertions.
func ruleSet(diags []ast.Diagnostic) map[string]bool {
	out := map[string]bool{}
	for _, d := range diags {
		out[d.Rule] = true
	}
	return out
}

func TestValidateCleanObject(t *testing.T) {
	// RFC 2622 §3.1 makes descr, tech-c, mnt-by, changed and source mandatory.
	rfc := parse(`route:   192.0.2.0/24
descr:   Example route
origin:  AS65000
tech-c:  EX1-RIPE
mnt-by:  MAINT-EX
changed: ops@example.net 20200101
source:  RADB
`)
	if d := RFCStrict.Validate(rfc); len(d) != 0 {
		t.Errorf("RFCStrict.Validate RFC-conformant route = %+v, want none", d)
	}
	ripe := parse(`route:   192.0.2.0/24
origin:  AS65000
mnt-by:  MAINT-EX
source:  RIPE
`)
	if d := RIPE.Validate(ripe); len(d) != 0 {
		t.Errorf("RIPE.Validate clean route = %+v, want none", d)
	}
}

func TestValidateUnknownAttr(t *testing.T) {
	// created: is generated by the RIPE Database, not an RFC attribute:
	// RFC-strict flags it, RIPE tolerates it. (changed: is RFC 2622 §3.1.)
	o := parse(`route:   192.0.2.0/24
descr:   Example route
origin:  AS65000
tech-c:  EX1-RIPE
mnt-by:  MAINT-EX
changed: ops@example.net 20200101
created: 2020-01-01T00:00:00Z
source:  RIPE
`)
	strict := RFCStrict.Validate(o)
	if len(strict) != 1 || strict[0].Rule != "dict/unknown-attr" {
		t.Errorf("RFCStrict diags = %+v, want exactly one dict/unknown-attr for created:", strict)
	}
	if ripe := RIPE.Validate(o); len(ripe) != 0 {
		t.Errorf("RIPE flagged created:, diags = %+v", ripe)
	}
}

func TestValidateMissingRequired(t *testing.T) {
	o := parse(`route:  192.0.2.0/24
origin: AS65000
mnt-by: MAINT-EX
`) // no source:
	d := RFCStrict.Validate(o)
	if !ruleSet(d)["dict/missing-required"] {
		t.Errorf("missing source: not reported, diags = %+v", d)
	}
}

func TestValidateCardinality(t *testing.T) {
	o := parse(`route:  192.0.2.0/24
origin: AS65000
origin: AS65001
mnt-by: MAINT-EX
source: RIPE
`) // origin is single-valued
	d := RFCStrict.Validate(o)
	if !ruleSet(d)["dict/cardinality"] {
		t.Errorf("duplicate origin: not reported, diags = %+v", d)
	}
}

func TestValidateUnknownClass(t *testing.T) {
	o := parse("frobnicate: whatever\nsource: RIPE\n")
	d := RIPE.Validate(o)
	if len(d) != 1 || d[0].Rule != "dict/unknown-class" {
		t.Errorf("unknown class diags = %+v, want one dict/unknown-class", d)
	}
}
