package object

import (
	"strings"
	"testing"

	"github.com/rkolesnichenko/rpsl/ast"
)

// ruleSet collects the diagnostic rules present, for order-independent assertions.
func ruleSet(diags []ast.Diagnostic) map[string]bool {
	out := map[string]bool{}
	for _, d := range diags {
		out[d.Rule] = true
	}
	return out
}

func TestValidateCleanObject(t *testing.T) {
	// RFC 2622 §3.1 makes descr, tech-c, mnt-by, changed and source mandatory.
	rfc := parse(`route:   192.0.2.0/24
descr:   Example route
origin:  AS65000
tech-c:  EX1-RIPE
mnt-by:  MAINT-EX
changed: ops@example.net 20200101
source:  RADB
`)
	if d := RFCStrict.Validate(rfc); len(d) != 0 {
		t.Errorf("RFCStrict.Validate RFC-conformant route = %+v, want none", d)
	}
	ripe := parse(`route:   192.0.2.0/24
origin:  AS65000
mnt-by:  MAINT-EX
source:  RIPE
`)
	if d := RIPE.Validate(ripe); len(d) != 0 {
		t.Errorf("RIPE.Validate clean route = %+v, want none", d)
	}
}

func TestValidateUnknownAttr(t *testing.T) {
	// created: is generated by the RIPE Database, not an RFC attribute:
	// RFC-strict flags it, RIPE tolerates it. (changed: is RFC 2622 §3.1.)
	o := parse(`route:   192.0.2.0/24
descr:   Example route
origin:  AS65000
tech-c:  EX1-RIPE
mnt-by:  MAINT-EX
changed: ops@example.net 20200101
created: 2020-01-01T00:00:00Z
source:  RIPE
`)
	strict := RFCStrict.Validate(o)
	if len(strict) != 1 || strict[0].Rule != "dict/unknown-attr" {
		t.Errorf("RFCStrict diags = %+v, want exactly one dict/unknown-attr for created:", strict)
	}
	// The RIPE templates have created: but no changed: (removed from the RIPE
	// Database) and no tech-c: on routes, so RIPE flags exactly those two.
	ripe := RIPE.Validate(o)
	if len(ripe) != 2 || ripe[0].Rule != "dict/unknown-attr" || !strings.Contains(ripe[0].Message, `"tech-c"`) ||
		!strings.Contains(ripe[1].Message, `"changed"`) {
		t.Errorf("RIPE diags = %+v, want dict/unknown-attr for tech-c: and changed:", ripe)
	}
	ripeRoute := parse("route: 192.0.2.0/24\norigin: AS65000\nmnt-by: MAINT-EX\ncreated: 2020-01-01T00:00:00Z\nsource: RIPE\n")
	if d := RIPE.Validate(ripeRoute); len(d) != 0 {
		t.Errorf("RIPE flagged a template-valid route: %+v", d)
	}
}

func TestValidateMissingRequired(t *testing.T) {
	o := parse(`route:  192.0.2.0/24
origin: AS65000
mnt-by: MAINT-EX
`) // no source:
	d := RFCStrict.Validate(o)
	if !ruleSet(d)["dict/missing-required"] {
		t.Errorf("missing source: not reported, diags = %+v", d)
	}
}

// A required attribute with no value is as good as missing: it is reported
// at the attribute. An empty member of a one-of group does not satisfy it.
func TestValidateEmptyRequired(t *testing.T) {
	d := RIPE.Validate(parse("route: 192.0.2.0/24\norigin:\nmnt-by: MAINT-EX\nsource: RIPE\n"))
	if len(d) != 1 || d[0].Rule != "dict/missing-required" || !strings.Contains(d[0].Message, `"origin" is empty`) ||
		d[0].Span.StartLine != 2 {
		t.Errorf("empty origin: diags = %+v, want one dict/missing-required on line 2", d)
	}
	d = RIPE.Validate(parse("route: 192.0.2.0/24\norigin: AS1\nmnt-by: MAINT-EX\nsource: # none\n"))
	if len(d) != 1 || !strings.Contains(d[0].Message, `"source" is empty`) {
		t.Errorf("comment-only source: diags = %+v, want it reported empty", d)
	}
	o := parse("filter-set: FLTR-X\nfilter:\ntech-c: X1-RIPE\nadmin-c: X1-RIPE\nmnt-by: M\nsource: RIPE\n")
	if got := missingRequired(RIPE.Validate(o)); len(got) != 1 || !strings.Contains(got[0], "one of") {
		t.Errorf("empty filter: missing-required = %q, want the one-of group", got)
	}
}

func TestValidateCardinality(t *testing.T) {
	o := parse(`route:  192.0.2.0/24
origin: AS65000
origin: AS65001
mnt-by: MAINT-EX
source: RIPE
`) // origin is single-valued
	d := RFCStrict.Validate(o)
	if !ruleSet(d)["dict/cardinality"] {
		t.Errorf("duplicate origin: not reported, diags = %+v", d)
	}
}

func TestValidateUnknownClass(t *testing.T) {
	o := parse("frobnicate: whatever\nsource: RIPE\n")
	d := RIPE.Validate(o)
	if len(d) != 1 || d[0].Rule != "dict/unknown-class" {
		t.Errorf("unknown class diags = %+v, want one dict/unknown-class", d)
	}
}
